# MACN/macn_se_cosine_mitdb.yaml

TRAIN:
  PRE_TRAIN_EPOCHS: 100
  EPOCHS: 500
  LR: 0.01
  DECAY_RATE: 0.99
  DECAY_STEP: 300

SETTING:
  NETWORK: 'MACNN_SE_cosine'
  LOSS: 'EWLoss'
  DISTANCE: 'Cosine'
  BEAT_NUM: 0
  FIXED_LEN: 128
  UDA_NUM: 300
  CENTER: False
  ASPP_BN: True
  ASPP_ACT: True
  RE_TRAIN: False
  NORM_ALIGN: False
  INTER_LOSS: True
  INTRA_LOSS: True
  DILATIONS: (1, 6, 12, 18)
  ACT: 'relu'
  SEED: 0

PARAMETERS:
  W_L2: 0.0
  THRS: (0.99, 0.99, 0.95, 0.99)